@Library("jenlib@ebrains-4.0") _

withCcache() {
	wafDefaultPipeline(projects: ["flange"],
	                   setupOptions: "--release-branch=ebrains-4.0",
	                   container: [app: "dls-core"],
	                   notificationChannel: "#dls-software",
	                   enableClangFormatFullDiff: true,
	                   configureInstallOptions: "--build-profile=ci")
}
