@Library("jenlib") _

withCcache() {
	wafDefaultPipeline(projects: ["flange"],
	                   container: [app: "dls-core"],
	                   notificationChannel: "#dls-software",
	                   enableClangFormatFullDiff: true,
	                   configureInstallOptions: "--build-profile=ci")
}
