@Library("jenlib") _

wafDefaultPipeline(projects: ["flange"],
                   container: [app: "dls-core"],
                   notificationChannel: "#dls-software",
                   enableClangFormatFullDiff: true)
