#!/usr/bin/env python
from waflib.extras.test_base import summary

def depends(ctx):
    ctx('flange')


def options(opt):
    pass


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')

    cfg.check(
        compiler='cxx',
        features='cxx pyembed',
        uselib_store='PYBIND11FLANGE',
        mandatory=True,
        header_name='pybind11/pybind11.h',
    )


def build(bld):
    bld(
        target='pyflange',
        source='../include/flange/flange.h',
        genpybind_tags='flange',
        features='genpybind cxx cxxshlib pyext pyembed',
        use=['flange', 'PYBIND11FLANGE'],
        install_path='${PREFIX}/lib',
        linkflags='-Wl,-z,defs',
    )

    bld.add_post_fun(summary)
