#!/usr/bin/env python
from waflib.extras.test_base import summary

def depends(ctx):
    ctx('flange')


def options(opt):
    pass


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('python')
    cfg.check_python_version()
    cfg.check_python_headers()
    cfg.load('pytest')
    cfg.load('genpybind')


def build(bld):
    bld(
        target='pyflange',
        source='../include/flange/flange.h',
        genpybind_tags='flange',
        features='genpybind cxx cxxshlib pyext',
        use=['flange'],
    )

    bld.add_post_fun(summary)
